Perfume_shop/Perfume_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('shop.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Perfume_shop/shop/urls.py
from django.urls import path

from shop import views



urlpatterns = [
    path('',views.HomePageView.as_view(),name='home_page'),
    path('perfumes/',views.PerfumeListView.as_view(),name='perfume_list'),
    path('perfumes/cat/<cat>', views.PerfumeListView.as_view(), name='perfume_categories_list'),
    path('perfumes/<pk>/',views.PerfumeDetailView.as_view(), name='perfume_detail'),
    path('perfumes/cat/<str:cat>/', views.PerfumeCategoriesListView.as_view(), name='perfume_categories_list'),
    path('about-us/',views.About.as_view(),name='about_page'),
    path('contact-us/',views.ContactUsView.as_view(),name='Contact_us_page'),
    path('search/',views.search,name='search_page')

]

Perfume_shop/shop/models.py
from django.db import models




class PerfumeCategory(models.Model):
    title = models.CharField(max_length=300,verbose_name='دسته بندی محصول')
    is_active = models.BooleanField(verbose_name='فعال / غیرفعال')
    is_delete = models.BooleanField(verbose_name='حذف شده / نشده')
    url_title = models.CharField(max_length=300, db_index=True, verbose_name='عنوان در url')

    def __str__(self):
        return f'({self.title} - {self.url_title})'

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'




class Perfume(models.Model):
    title = models.CharField(max_length=300,verbose_name='نام محصول')
    category = models.ManyToManyField(PerfumeCategory,related_name='perfume_categories',verbose_name='دسته بندی عطر')
    image = models.ImageField(upload_to='image/products',verbose_name='عکس محصول')
    brand = models.CharField(max_length=300, verbose_name='برند', null=True, blank=True)
    short_description = models.CharField(max_length=360, db_index=True, null=True, verbose_name='توضیحات کوتاه')
    description = models.TextField(verbose_name='توضیحات اصلی', db_index=True)
    slug = models.SlugField(default="", null=False, db_index=True, blank=True, max_length=200, unique=True,
                            verbose_name='عنوان در url')
    is_active = models.BooleanField(default=False, verbose_name='فعال / غیرفعال')
    is_delete = models.BooleanField(verbose_name='حذف شده / نشده')
    mil_price = models.PositiveIntegerField(verbose_name='قیمت هر میل',null=True,blank=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)



# class VolumePerfumePrice(models.Model):
#     volume = models.CharField(max_length=300,verbose_name='حجم عطر')
#     price = models.IntegerField(verbose_name='قیمت عطر')
#     perfume =models.ForeignKey(Perfume, on_delete=models.CASCADE, related_name='volumes_perfume')
#
#     class Meta:
#         verbose_name = 'قیمت عطر'
#         verbose_name_plural = 'قیمت عطرها'
#
#
#
#     def __str__(self):
#         return f"{self.volume}میل-{self.price}تومان"


class VolumePerfumePrice(models.Model):
    volume = models.CharField(max_length=300,verbose_name='حجم عطر')
    price = models.IntegerField(verbose_name='قیمت عطر')
    perfume = models.ForeignKey('Perfume', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'قیمت عطر'
        verbose_name_plural = 'قیمت عطرها'



    def __str__(self):
        return f"{self.volume}میل-{self.price}تومان"



class PerfumeVisit(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    perfume = models.ForeignKey('Perfume', on_delete=models.CASCADE)
    ip = models.CharField(max_length=30, verbose_name='آی پی کاربر')


    def __str__(self):
        return f'{self.perfume.title} / {self.ip}'

    class Meta:
        verbose_name = 'بازدید محصول'
        verbose_name_plural = 'بازدیدهای محصول'





class SiteSetting(models.Model):
    site_name = models.CharField(max_length=200, verbose_name='نام سایت')
    site_url = models.CharField(max_length=200, verbose_name='دامنه سایت')
    address = models.CharField(max_length=200, verbose_name='آدرس')
    phone = models.CharField(max_length=200, null=True, blank=True, verbose_name='تلفن')
    fax = models.CharField(max_length=200, null=True, blank=True, verbose_name='فکس')
    email = models.CharField(max_length=200, null=True, blank=True, verbose_name='ایمیل')
    copy_right = models.TextField(verbose_name='متن کپی رایت سایت')
    about_us_text = models.TextField(verbose_name='متن درباره ما سایت')
    site_logo = models.ImageField(upload_to='images/site-setting/', verbose_name='لوگو سایت')
    is_main_setting = models.BooleanField(verbose_name='تنظیمات اصلی')
    image = models.ImageField(upload_to='images/site-setting/',verbose_name='تصویر درباره ما')

    class Meta:
        verbose_name = 'تنظیمات سایت'
        verbose_name_plural = 'تنظیمات'

    def __str__(self):
        return self.site_name


class FooterLinkBox(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')

    class Meta:
        verbose_name = 'دسته بندی لینک های فوتر'
        verbose_name_plural = 'دسته بندی های لینک های فوتر'

    def __str__(self):
        return self.title


class FooterLink(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url = models.URLField(max_length=500, verbose_name='لینک')
    footer_link_box = models.ForeignKey(to=FooterLinkBox, on_delete=models.CASCADE, verbose_name='دسته بندی')

    class Meta:
        verbose_name = 'لینک فوتر'
        verbose_name_plural = 'لینک های فوتر'

    def __str__(self):
        return self.title


class SiteBanner(models.Model):
    class SiteBannerPositions(models.TextChoices):
        product_list = 'product_list', 'صفحه لیست محصولات',
        product_detail = 'product_detail', 'صفحه ی جزییات محصولات',
        about_us = 'about_us', 'درباره ما'

    title = models.CharField(max_length=200, verbose_name='عنوان بنر')
    url = models.URLField(max_length=400, null=True, blank=True, verbose_name='آدرس بنر')
    image = models.ImageField(upload_to='images/banners', verbose_name='تصویر بنر')
    is_active = models.BooleanField(verbose_name='فعال / غیرفعال')
    position = models.CharField(max_length=200, choices=SiteBannerPositions.choices, verbose_name='جایگاه نمایشی')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'بنر تبلیغاتی'
        verbose_name_plural = 'بنرهای تبلیغاتی'


class ContactUs(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان')
    email = models.EmailField(max_length=300, verbose_name='ایمیل')
    full_name = models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')
    message = models.TextField(verbose_name='متن تماس با ما')
    created_date = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    response = models.TextField(verbose_name='متن پاسخ تماس با ما', null=True, blank=True)
    is_read_by_admin = models.BooleanField(verbose_name='خوانده شده توسط ادمین', default=False)

    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'لیست تماس با ما'

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    image = models.ImageField(upload_to='images')

Perfume_shop/templates/shared/layout.html
<!DOCTYPE html>
{% load render_partial %}
<html lang="en" dir="rtl">

<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<meta name="keywords" content="HTML5 Template">
	<meta name="description" content="Molla - Bootstrap eCommerce Template">
	<meta name="author" content="p-themes">
	<!-- Favicon -->
    {% include 'shared/site_header_refrences.html' %}
</head>

<body>
	<div class="page-wrapper">
		{% block background %}{% endblock %}
            
            {% render_partial 'shop.views.site_header_component' %}
			
			{% block slider %}{% endblock %}
		</div>
		
        {% block content %}{% endblock %}

		{% render_partial 'shop.views.site_footer_component' %}
	
	
	<button id="scroll-top" title="بازگشت به بالا"><i class="icon-arrow-up"></i></button>

	{% render_partial 'shop.views.mobile_header_component' %}

    
{% include 'shared/site_footer_references.html' %}
</body>

</html>

Perfume_shop/templates/shared/mobile_menu_component.html
<div class="mobile-menu-overlay">
	</div><!-- End .mobil-menu-overlay -->
	<div class="mobile-menu-container mobile-menu-light">
		<div class="mobile-menu-wrapper">
			<span class="mobile-menu-close"><i class="icon-close"></i></span>

			<form action="#" method="get" class="mobile-search">
				<label for="mobile-search" class="sr-only">جستجو</label>
				<input type="search" class="form-control" name="mobile-search" id="mobile-search"
					placeholder="جستجو در ..." required>
				<button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
			</form>

			<ul class="nav nav-pills-mobile nav-border-anim" role="tablist">
				<li class="nav-item">
					<a class="nav-link active" id="mobile-menu-link" data-toggle="tab" href="#mobile-menu-tab"
						role="tab" aria-controls="mobile-menu-tab" aria-selected="true">منو</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="mobile-cats-link" data-toggle="tab" href="#mobile-cats-tab" role="tab"
						aria-controls="mobile-cats-tab" aria-selected="false">دسته بندی ها</a>
				</li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane fade show active" id="mobile-menu-tab" role="tabpanel"
					aria-labelledby="mobile-menu-link">
					<nav class="mobile-nav">
						<ul class="mobile-menu">
							<li class="active">
								<a href="index-1.html">خانه</a>
							</li>
							<li>
								<a href="category.html">فروشگاه</a>
								<ul>
									<li><a href="category-list.html">فروشگاه لیست</a></li>
                            <li><a href="gift-cart.html">کارت هدیه</a></li>
									<li><a href="dashboard.html">داشبورد</a></li>
								</ul>
							</li>
							<li>
								<a href="product.html" class="sf-with-ul">محصولات</a>
								<ul>
									<li><a href="product.html">پیش فرض</a></li>
									<li><a href="product-centered.html">توضیحات وسط چین</a></li>
									<li><a href="product-extended.html"><span>توضیحات گسترده<span
													class="tip tip-new">جدید</span></span></a></li>
									<li><a href="product-gallery.html">گالری</a></li>
									<li><a href="product-sticky.html">اطلاعات چسبیده</a></li>
									<li class=""><a href="product-sidebar.html">صفحه جمع با سایدبار</a></li>
									<li><a href="product-fullwidth.html">تمام صفحه</a></li>
									<li><a href="product-masonry.html">اطلاعات چسبیده ماسونری</a></li>
                                                        <li><a href="product-new-design.html">طراحی جدید</a></li>
								</ul>
							</li>
							<li>
								<a href="#">صفحات</a>
								<ul>
									<li>
										<a href="about.html" class="sf-with-ul">درباره ما</a>

										<ul style="display: none;">
											<li><a href="about.html">درباره ما 01</a></li>
											<li><a href="about-2.html">درباره ما 02</a></li>
										</ul>
									</li>
									<li>
										<a href="contact.html" class="sf-with-ul">تماس با ما</a>

										<ul style="display: none;">
											<li><a href="contact.html">تماس با ما 01</a></li>
											<li><a href="contact-2.html">تماس با ما 02</a></li>
										</ul>
									</li>
									<li><a href="login.html">ورود</a></li>
                                        <li><a href="forget-password.html">فراموشی رمز عبور</a></li>
									<li><a href="track-order.html">پیگیری سفارش</a></li>
									<li><a href="faq.html">سوالات متداول</a></li>
									<li><a href="404.html">خطای 404</a></li>
									<li><a href="coming-soon.html">به زودی</a></li>
                                        <li><a href="coming-soon-2.html">به زودی 2</a></li>
								</ul>
							</li>
							<li>
								<a href="blog.html">اخبار</a>

								<ul>
									<li class=""><a href="blog.html">کلاسیک</a></li>
									<li><a href="blog-listing.html">لیست</a></li>
									<li>
										<a href="#" class="sf-with-ul">شبکه بندی</a>
										<ul style="display: none;">
											<li><a href="blog-grid-2cols.html">2 ستونه</a></li>
											<li><a href="blog-grid-3cols.html">3 ستونه</a></li>
											<li><a href="blog-grid-4cols.html">4 ستونه</a></li>
											<li><a href="blog-grid-sidebar.html">با سایدبار</a></li>
										</ul>
									</li>
									<li>
										<a href="#" class="sf-with-ul">سایز های مختلف</a>
										<ul style="display: none;">
											<li><a href="blog-masonry-2cols.html">2 ستونه</a></li>
											<li><a href="blog-masonry-3cols.html">3 ستونه</a></li>
											<li><a href="blog-masonry-4cols.html">4 ستونه</a></li>
											<li><a href="blog-masonry-sidebar.html">با سایدبار</a></li>
										</ul>
									</li>
									<li>
										<a href="#" class="sf-with-ul">ماسک</a>
										<ul style="display: none;">
											<li><a href="blog-mask-grid.html">نوع 1</a></li>
											<li><a href="blog-mask-masonry.html">نوع 2</a></li>
										</ul>
									</li>
									<li>
										<a href="#" class="sf-with-ul">پست تکی</a>
										<ul style="display: none;">
											<li><a href="single.html">پیش فرض با سایدبار</a></li>
											<li><a href="single-fullwidth.html">تمام صفحه بدون سایدبار</a></li>
											<li><a href="single-fullwidth-sidebar.html">تمام صفحه باسایدبار</a>
											</li>
										</ul>
									</li>
								</ul>
							</li>
							<li>
								<a href="elements-list.html">عناصر طراحی</a>
								<ul>
									<li class=""><a href="elements-products.html">محصولات</a></li>
									<li><a href="elements-typography.html">تایپوگرافی</a></li>
									<li><a href="elements-titles.html">عناوین</a></li>
									<li><a href="elements-banners.html">بنرها</a></li>

									<li><a href="elements-product-category.html">دسته بندی محصولات</a></li>
									<li><a href="elements-video-banners.html">بنرهای ویدیویی</a></li>
									<li><a href="elements-buttons.html">دکمه ها</a></li>
									<li><a href="elements-accordions.html">آکاردئون</a></li>
                                        <li><a href="elements-lookbook.html">لوک بوک</a></li>
									<li><a href="elements-tabs.html">تب ها</a></li>
									<li><a href="elements-testimonials.html">توصیف و نقل قول</a></li>
									<li><a href="elements-blog-posts.html">اخبار</a></li>
									<li><a href="elements-portfolio.html">نمونه کار</a></li>
									<li><a href="elements-cta.html">پاسخ به عمل</a></li>
									<li><a href="elements-icon-boxes.html">باکس های آیکون</a></li>
								</ul>
							</li>
						</ul>
					</nav><!-- End .mobile-nav -->
				</div><!-- .End .tab-pane -->
				<div class="tab-pane fade" id="mobile-cats-tab" role="tabpanel" aria-labelledby="mobile-cats-link">
					<nav class="mobile-cats-nav">
						<ul class="mobile-cats-menu">
							<li><a class="mobile-cats-lead" href="#">پیشنهاد روزانه</a></li>
							<li><a class="mobile-cats-lead" href="#">هدیه</a></li>
							<li><a href="#">تخت خواب</a></li>
							<li><a href="#">روشنایی</a></li>
							<li><a href="#">مبلمان</a></li>
							<li><a href="#">فضای ذخیره سازی</a></li>
							<li><a href="#">میز وصندلی</a></li>
							<li><a href="#">دکور </a></li>
							<li><a href="#">کابینت</a></li>
							<li><a href="#">قهوه</a></li>
							<li><a href="#">مبلمان خارج از منزل </a></li>
						</ul><!-- End .mobile-cats-menu -->
					</nav><!-- End .mobile-cats-nav -->
				</div><!-- .End .tab-pane -->
			</div><!-- End .tab-content -->

			<div class="social-icons">
				<a href="#" class="social-icon" target="_blank" title="اینستاگرام"><i class="icon-instagram"></i></a>
			</div><!-- End .social-icons -->
		</div><!-- End .mobile-menu-wrapper -->
	</div><!-- End .mobile-menu-container -->

Perfume_shop/templates/shared/search.html
{% extends 'shared/layout.html' %}
{% load poll_extras %}
{% load thumbnail %}

{% block title %}
	صفحه جست و جو
{% endblock %}



{% block background %}
	   <div class="background" style="background-color: mediumpurple">
{% endblock %}



{% block content %}
	<main class="main">
            <div class="page-header text-center" style="background-image: url('/static/assets/images/slider/vecteezy_purple-gradient-background-vector-art_17067277.jpg')">
                <div class="container">
                    <h1 class="page-title">نتایج جستجو</h1>
                </div><!-- End .container -->
            </div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-2">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home_page' %}">خانه</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'perfume_list' %}">فروشگاه</a></li>
                        <li class="breadcrumb-item active" aria-current="page">نتایج جستجو</li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="toolbox">
                                <div class="toolbox-left">
                                    <div class="toolbox-info">
                                        نمایش <span>{{ perfume_search.paginator.count }}</span> محصول
                                    </div><!-- End .toolbox-info -->
                                </div><!-- End .toolbox-left -->

                            </div><!-- End .toolbox -->

                        	 {% if perfume_search %}
                        	 	  {% for perfume in perfume_search %}
                           	 <div class="products mb-3">
                                <div class="product product-list">
                                    <div class="row">
                                        <div class="col-6 col-lg-3">
                                            <figure class="product-media">
                                                <a href="{% url 'perfume_detail' pk=perfume.id %}">
                                                   {% thumbnail perfume.image "185x185" quality=90 crop='center' as im %}
                                <img src="{{ im.url }}" class="mx-auto mb-5" alt="image">
                                {% endthumbnail %}
                                                </a>
                                            </figure><!-- End .product-media -->
                                        </div><!-- End .col-sm-6 col-lg-3 -->

                                        <div class="col-6 col-lg-3 order-lg-last">
                                            <div class="product-list-action">
                                                <div class="product-price">
                                                    {{ perfume.mil_price | three_digits_currency }}(هرمیلی لیتر)
                                                </div><!-- End .product-price -->
                                                <a href="{% url 'perfume_detail' pk=perfume.id %}" class="btn-product btn-cart"><span>افزودن به سبد
                                                        خرید</span></a>
                                            </div><!-- End .product-list-action -->
                                        </div><!-- End .col-sm-6 col-lg-3 -->

                                        <div class="col-lg-6">
                                            <div class="product-body product-action-inner">
                                                <div class="product-cat">
                                                   {% for category in perfume.category.all %}
                                                        {{ category.title }}
                                                    {% endfor %}
                                                </div><!-- End .product-cat -->
                                                <h3 class="product-title"><a href="{% url 'perfume_detail' pk=perfume.id %}">{{ perfume.title }}</a>
                                                </h3><!-- End .product-title -->
                                                <div class="product-content">
                                                    <p class="short">{{ perfume.short_description }}</p>
                                                </div><!-- End .product-content -->
                                            </div><!-- End .product-body -->
                                        </div><!-- End .col-lg-6 -->
                                    </div><!-- End .row -->
                                </div><!-- End .product -->
                            </div><!-- End .products -->
                           {% endfor %}
                                 {% else %}
                                 <div class="products mb-3">
                                 <h3>محصول مورد نظر یافت نشد!</h3>
                                 <img src="/static/assets/images/products/search.PNG">
                                 </div>
                        	 {% endif %} 
                            
                        
                        
                        
                        
                        {% if perfume_search %}
                            <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if perfume_search.has_previous %}
                            <li class="page-item">
                                <a class="page-link page-link-prev" href="?search={{ request.GET.search }}&page={{ perfume_search.previous_page_number }}" aria-label="Previous" tabindex="-1">
                                    <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>قبلی
                                </a>
                            </li>
                        {% endif %}
                        
                        {% for num in perfume_search.paginator.page_range %}
                            {% if num == perfume_search.number %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?search={{ request.GET.search }}&page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if perfume_search.has_next %}
                            <li class="page-item">
                                <a class="page-link page-link-next" href="?search={{ request.GET.search }}&page={{ perfume_search.next_page_number }}" aria-label="Next">
                                    بعدی <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>
                                </a>
                            </li>
                        {% endif %}
                            </ul>
                            </nav>
                        {% endif %} 
                        </div><!-- End .col-lg-9 -->
                        
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->
    </div>{% endblock %}

Perfume_shop/templates/shared/site_footer_component.html
<footer class="footer mt-3">
			<div class="container service">
				<div class="row">
					<div class="col-sm-6 col-lg-3">
						<div class="icon-box icon-box-side">
							<span class="icon-box-icon">
								<i class="icon-rocket"></i>
							</span>

							<div class="icon-box-content">
								<h3 class="icon-box-title">ارسال رایگان</h3><!-- End .icon-box-title -->
								<p>برای سفارشات بالای یک میلیون تومان</p>
							</div><!-- End .icon-box-content -->
						</div><!-- End .icon-box -->
					</div><!-- End .col-sm-6 col-lg-4 -->

					<div class="col-sm-6 col-lg-3">
						<div class="icon-box icon-box-side">
							<span class="icon-box-icon">
								<i class="icon-rotate-left"></i>
							</span>

							<div class="icon-box-content">
								<h3 class="icon-box-title">بازگشت کالا</h3><!-- End .icon-box-title -->
								<p>به مدت 7 روز</p>
							</div><!-- End .icon-box-content -->
						</div><!-- End .icon-box -->
					</div><!-- End .col-sm-6 col-lg-4 -->

					<div class="col-sm-6 col-lg-3">
						<div class="icon-box icon-box-side">
							<span class="icon-box-icon">
								<i class="icon-info-circle"></i>
							</span>

							<div class="icon-box-content">
								<h3 class="icon-box-title">ضمانت اصل بودن کالا</h3>
								<!-- End .icon-box-title -->
							</div><!-- End .icon-box-content -->
						</div><!-- End .icon-box -->
					</div><!-- End .col-sm-6 col-lg-4 -->

					<div class="col-sm-6 col-lg-3">
						<div class="icon-box icon-box-side">
							<span class="icon-box-icon">
								<i class="icon-life-ring"></i>
							</span>

							<div class="icon-box-content">
								<h3 class="icon-box-title">پشتیبانی ما</h3><!-- End .icon-box-title -->
								<p>ارائه خدمات 24 ساعته / 7 روز هفته</p>
							</div><!-- End .icon-box-content -->
						</div><!-- End .icon-box -->
					</div><!-- End .col-sm-6 col-lg-4 -->
				</div>
			</div>

			<div class="footer-middle">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-12">
							<div class="widget widget-about">
								<img src="{{ site_setting.site_logo.url }}" class="footer-logo" alt="Footer Logo"
									width="110" height="25">
								<p>{{ site_setting.about_us_text }}</p>

								<div class="social-icons">
									<a href="#" class="social-icon" title="اینستاگرام" target="_blank"><i
											class="icon-instagram"></i></a>
								</div><!-- End .soial-icons -->
							</div><!-- End .widget about-widget -->
						</div><!-- End .col-sm-12 col-lg-3 -->

					{% for footer_link_box in footer_link_boxes %}
							<div class="col-lg-3 col-sm-4 col-md-4">
							<div class="widget">
								<h4 class="widget-title">{{ footer_link_box.title }}</h4><!-- End .widget-title -->
                        {% for link in footer_link_box.footerlink_set.all %}
                            <ul class="widget-list">
                                                            <li><a href="{{ link.url }}">{{ link.title }}</a></li>
                                                        </ul><!-- End .widget-list -->
                        {% endfor %}

								
							</div><!-- End .widget -->
						</div><!-- End .col-lg-3 col-sm-4 col-md-4 -->
					{% endfor %}
					
                        
					</div>
				</div>
			</div>
			<div class="footer-bottom">
				<div class="container">
					<p class="footer-copyright">{{ site_setting.copy_right }}</p>
					<!-- End .footer-copyright -->

				</div><!-- End .widget-about-info -->
			</div><!-- End .container -->
        </footer>

Perfume_shop/templates/shared/site_footer_references.html
	<script src="/static/assets/js/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="/static/assets/js/bootstrap.bundle.min.js"></script>
	<script src="/static/assets/js/jquery.hoverIntent.min.js"></script>
	<script src="/static/assets/js/jquery.waypoints.min.js"></script>
	<script src="/static/assets/js/superfish.min.js"></script>
	<script src="/static/assets/js/owl.carousel.min.js"></script>
	<script src="/static/assets/js/bootstrap-input-spinner.js"></script>
	<script src="/static/assets/js/jquery.plugin.min.js"></script>
	<script src="/static/assets/js/jquery.countdown.min.js"></script>
	<script src="/static/assets/js/jquery.magnific-popup.min.js"></script>
	<!-- Main JS File -->
	<script src="/static/assets/js/main.js"></script>
	<script src="/static/assets/js/demos/demo-24.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="/static/assets/js/test_basket.js"></script>
    <script src="/static/assets/js/custom.js"></script>
    